In [1]:
import pandas as pd # data loading, cleaning, time-series handling
import numpy as np # numerical operations

# Plot trends, seasonality, predictions vs actual
import matplotlib.pyplot as plt
import seaborn as sns

# time series handling
from datetime import datetime

# preprcessing
from sklearn.preprocessing import StandardScaler, MinMaxScaler
from sklearn.model_selection import train_test_split

In [3]:
# MODELS
from sklearn.linear_model import LinearRegression

#Evaluation Metrics
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

# Model Saving & Loading
import joblib

In [18]:
df = pd.read_csv("../data/household_power_consumption.txt", sep=';')

C:\Users\osumb\AppData\Local\Temp\ipykernel_19176\3253272748.py:1: DtypeWarning: Columns (2,3,4,5,6,7) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("../data/household_power_consumption.txt", sep=';')

In [19]:
df.head()

,Date,Time,Global_active_power,Global_reactive_power,Voltage,Global_intensity,Sub_metering_1,Sub_metering_2,Sub_metering_3
0,16/12/2006,17:24:00,4.216,0.418,234.840,18.400,0.000,1.000,17.0
1,16/12/2006,17:25:00,5.360,0.436,233.630,23.000,0.000,1.000,16.0
2,16/12/2006,17:26:00,5.374,0.498,233.290,23.000,0.000,2.000,17.0
3,16/12/2006,17:27:00,5.388,0.502,233.740,23.000,0.000,1.000,17.0
4,16/12/2006,17:28:00,3.666,0.528,235.680,15.800,0.000,1.000,17.0

In [20]:
# viewing no of columns and rows
df.shape

(2075259, 9)

In [21]:
# data types
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2075259 entries, 0 to 2075258
Data columns (total 9 columns):
 #   Column                 Dtype
---  ------                 -----
 0   Date                   object
 1   Time                   object
 2   Global_active_power    object
 3   Global_reactive_power  object
 4   Voltage                object
 5   Global_intensity       object
 6   Sub_metering_1         object
 7   Sub_metering_2         object
 8   Sub_metering_3         float64
dtypes: float64(1), object(8)
memory usage: 142.5+ MB

### Fix data types

In [25]:
# Replace "?" with NaN
df.replace('?', pd.NA, inplace=True)

# Convert all columns except Date & Time
cols = df.columns.drop(['Date', 'Time'])
df[cols] = df[cols].apply(pd.to_numeric, errors='coerce')

In [26]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2075259 entries, 0 to 2075258
Data columns (total 9 columns):
 #   Column                 Dtype
---  ------                 -----
 0   Date                   float64
 1   Time                   float64
 2   Global_active_power    float64
 3   Global_reactive_power  float64
 4   Voltage                float64
 5   Global_intensity       float64
 6   Sub_metering_1         float64
 7   Sub_metering_2         float64
 8   Sub_metering_3         float64
dtypes: float64(9)
memory usage: 142.5 MB

### Handle Missing values

In [27]:
df.isnull().sum()

Date                     2075259
Time                     2075259
Global_active_power        25979
Global_reactive_power      25979
Voltage                    25979
Global_intensity           25979
Sub_metering_1             25979
Sub_metering_2             25979
Sub_metering_3             25979
dtype: int64

In [28]:
# drop null values
df.dropna(inplace=True)

In [29]:
df.isnull().sum()

Date                     0
Time                     0
Global_active_power      0
Global_reactive_power    0
Voltage                  0
Global_intensity         0
Sub_metering_1           0
Sub_metering_2           0
Sub_metering_3           0
dtype: int64

In [30]:
df.head()

Empty DataFrame
Columns: [Date, Time, Global_active_power, Global_reactive_power, Voltage, Global_intensity, Sub_metering_1, Sub_metering_2, Sub_metering_3]
Index: []

### creating a date-time index

In [31]:
df['datetime'] = pd.to_datetime(df['Date'] + ' ' + df['Time'])

df.set_index('datetime', inplace=True)

df.drop(['Date', 'Time'], axis=1, inplace=True)

UFuncTypeError: ufunc 'add' did not contain a loop with signature matching types (dtype('float64'), dtype('<U1')) -> None